# https://docs.travis-ci.com/user/multi-os/
# https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
dist: focal
sudo: required
language: python
python: 3.7

env:
-   MAX_CPU_PERCENT=20 MAX_MEM_PERCENT=5

install:
-   sudo apt-key update
-   sudo apt-get -yq update
-   sudo apt -yq install xvfb gnome-shell

# Install NodeJS from upstream, since the version that comes with Ubuntu is usually ancient.
-   sudo apt-get -yq install curl
#-   curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
#-   sudo apt-get install -yq nodejs
-   curl -sL https://deb.nodesource.com/setup_14.x -o nodesource_setup.sh
-   sudo bash nodesource_setup.sh
-   sudo apt install nodejs
-   node -v

# Necessary on some versions of Ubuntu, which has a malformed npm/nodejs package.
-   sudo bash -c "[ ! -f /usr/bin/nodejs ] && ln -s /usr/bin/node /usr/bin/nodejs || true"
-   which nodejs
-   which node

# Install NPM from upstream.
-   git clone git://github.com/npm/cli.git
-   cd cli/scripts
-   chmod +x install.sh
-   sudo ./install.sh
-   cd ../..

-   sudo npm install -g eslint

before_script:
  - "export DISPLAY=:99.0"
  - which Xvfb
  - which start-stop-daemon
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - sleep 3 # give xvfb some time to start
  - ps aux|grep -i Xvfb|grep -v grep
  - sudo gnome-shell &
  - sleep 3 # give gnome-shell some time to start
  - journalctl /usr/bin/gnome-shell
  - tail -n 5 ~/.xsession-errors
  - ps aux|grep -i gnome-shell|grep -v grep

script:
-   set -e

# Clear initial gnome-shell errors we don't care about.
-   sudo journalctl /usr/bin/gnome-shell
-   sudo journalctl --rotate
-   sudo journalctl --vacuum-time=1s

# Show pre-extension gnome-shell performance.
-   ps -C gnome-shell -o %cpu,%mem,cmd || true

# Run JSlint check.
-   cd $TRAVIS_BUILD_DIR
-   ./checkjs.sh

# Install and enable extension.
-   sudo make install
-   gnome-shell-extension-tool --enable-extension=system-monitor@paradoxxx.zero.gmail.com

# Give extension time to run.
-   sleep 10

# Show post-extension gnome-shell performance.
-   ps -C gnome-shell -o %cpu,%mem,cmd
# Check CPU. On localhost with 2.80GHz x 4 takes ~3%, on Travis ~15%.
-   bash -c '[[ $(bc <<< "$(ps -C gnome-shell -o %cpu|tail -1) < $MAX_CPU_PERCENT") -eq 1 ]]'
# Check memory. On localhost with 32GB of memory, ~0.6%, on Travis ~3%.
-   bash -c '[[ $(bc <<< "$(ps -C gnome-shell -o %mem|tail -1) < $MAX_MEM_PERCENT") -eq 1 ]]'
# Confirm extension hasn't thrown any errors.
-   sudo journalctl /usr/bin/gnome-shell
-   sudo journalctl /usr/bin/gnome-shell|grep "\-\- No entries \-\-"
