# https://docs.travis-ci.com/user/multi-os/
# https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
dist: xenial
sudo: required
language: python
python: 3.7

services:
-   docker

install:
-   sudo apt-key update
-   sudo apt-get -yq update

script:
-   ./run_docker_tests.sh ubuntu1804
-   ./run_docker_tests.sh ubuntu2004
